version: 2.1

jobs:
  build:
    docker:
      - image: cimg/clojure:1.11.1
    steps:
      - checkout
      - run: clojure -T:build ci
  lint:
    docker:
      - image: cimg/clojure:1.11.1
    steps:
      - checkout
      - run:
          name: Linting
          command: |
            clojure -M:clj-kondo --lint src test
            clojure -M:cljfmt check

workflows:
  build:
    jobs:
      - build
      - lint
